### ISSUE TITLE
Bot fail on startup

### ISSUE THREAD

**Issue by kittylegitcheck** [barisbored/slash-level#1]
![image](https://user-images.githubusercontent.com/79789524/112297865-ac61b680-8c96-11eb-929b-9e98e1e144a2.png)
nonde.js above
typescript below
![image](https://user-images.githubusercontent.com/79789524/112298333-314cd000-8c97-11eb-95e5-0be55e847e0f.png)

**Comment by barbarbar338** [comment]
run `npm run build` command first and then run `npm run start:prod`

**Comment by barbarbar338** [comment]
I think your problem is solved
