### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by mr-far** [barisbored/slash-level#3]
Add something with buttons, selects, modals

**Comment by barbarbar338** [comment]
for what?

**Comment by mr-far** [comment]
> for what?

Like for bot invitation, add rank card for `/rank` and after accessibility to change background with buttons or select menu for sorting members in leaderboard

**Comment by barbarbar338** [comment]
well if you can, why don't you create a PR about this? That would be awesome! And closing this issue because there is no problem with functionality of the bot. I'll try to add some components.
