### ISSUE TITLE
image api problem

### ISSUE THREAD

**Issue by nanoeray** [barisbored/slash-level#5]
image api not works. which image library compatible with the system?

**Comment by barbarbar338** [comment]
It looks like image api is crashed for some reason. I'll fix it asap, no documentation is required for this.

**Comment by nanoeray** [comment]
[assets.zip](https://github.com/barbarbar338/slash-level/files/13786161/assets.zip)
i've implemented custom expressjs built-in image api for the bot. U can add it if you want.

[imageApi.zip](https://github.com/barbarbar338/slash-level/files/13786164/imageApi.zip)
example result:
![image](https://github.com/barbarbar338/slash-level/assets/4501601/598d91f8-1179-4f26-9e16-c29de3b82d7b)

**Comment by barbarbar338** [comment]
If you want you can create a PR that implements this image creator to bot instead of using an external api. That would be really appreciated.

**Comment by nanoeray** [comment]
i tried to push a branch but got 403 error

**Comment by barbarbar338** [comment]
You can not directly push changes to my repo. You have to fork this repo and push your changes to that fork. After pushing your changes to your fork you have to create a pull request.

**Comment by nanoeray** [comment]
created pr. please check before merge.
