### ISSUE TITLE
Fail on start.

### ISSUE THREAD

**Issue by HexLol** [barisbored/slash-level#7]
I keep on  recieving "libcrypto 1.1.0 is missing", I am running the bot on a hosting service so I need a work around.

**Comment by barbarbar338** [comment]
Where do you host the bot

**Comment by HexLol** [comment]
> Where do you host the bot

https://dash.witchly.host/servers.php

**Comment by barbarbar338** [comment]
I think you have to contact with witchly host support about this issue. As far as I see rn, they are providing their own "Discord Bot Hosting" option and it's probably a docker image (correct me if I'm wrong) which you can not directly install anything if they do not provide an interface to communicate with the container. If you can provide me mor information about how the things working in witch host then maybe I can help about it.

**Comment by barbarbar338** [comment]
Any updates? Can you also provide the full logs (don't forget to blur sensitive information)

**Comment by barbarbar338** [comment]
Closing because of no response. Feel free to open it if you have more questions :)

**Comment by nanoeray** [comment]
it was closed but the reason of this error, u are trying to run it on nodejs version 18 or higher with unsupported os. Node 18 wont work on CentOS 7. try to run it on Docker.
